4팀(파멸의 4오정) 발표용 코드
plain-bagel/mini-hackathon-2023-summer pull request #4
Opened 2023-06-16 15:46 UTC by sport0102

2023-06-16 17:28 UTC, renardyreveur approved these changes
파멸의 4오정! 🥇 1등 축하드립니다!! 👍

2023-06-16 17:32 UTC, renardyreveur requested changes

2023-06-16 17:32 UTC, renardyreveur commented on team-04/front.py
> +prompt = st.text_area("GPT에게 요청할 내용")
혹시 어딘가에 `setting`과 `prompt` 예제를 올려주실 수 있으실까요??

2023-06-17 13:15 UTC, sport0102 commented on team-04/front.py
> +prompt = st.text_area("GPT에게 요청할 내용")
README에 넣어두었습니다!
[링크](https://www.notion.so/plainbagel/4b9131ab1cbe4655b41fc0fa825af91c?pvs=4d)

2023-06-17 13:45 UTC, renardyreveur commented on team-04/front.py
> +prompt = st.text_area("GPT에게 요청할 내용")
앗 ㅠㅠ 리드미 안의 링크를 타고 들어가 확인했어야 했는데,, 죄송합니다ㅠㅠ

2023-06-17 13:46 UTC, renardyreveur approved these changes

2023-06-17 13:46 UTC, merged